[package]
name = "rustbashrewards"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.9.0"
anyhow = "1.0.40"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.0", features = ["full"] }

[profile.release]
lto = true
